# 配置文件
redis:
    host: 127.0.0.1
    port: 6379
    db: 1
    pwd: xxxxxxxxxx

web:
    host: '0.0.0.0:8888'
    redirect_uri: 'http://getfeishuid.xxxxxxx.com:8888/uid'

feishu:
    appid: cli_xxxxxxxxxxxxxxxxxxxxxxx
    appsecret: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx